PAGE_TITLE = "Q/A Chatbot"
OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_TEMPERATURE = 0.1
OLLAMA_MODEL = "qa-chatbot"
CHROMA_PERSIST_DIRECTORY = "./chroma_db"
CHROMA_COLLECTION = "qa-chatbot"
ELEVEN_LABS_API_KEY = "your-elevenlabs-api-key"
ELEVEN_LABS_VOICE_ID = "your-elevenlabs-voice-id"